import { relations } from "drizzle-orm"
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core"
import type { UIMessage } from "ai"

/**
 * The shape stored in `turn_usage.usage_breakdown` — see the column's own
 * comment below. Declared locally, as loosely-typed strings, rather than
 * imported from the app's model registry (`apps/web/lib/ai/model-registry.ts`,
 * `lib/ai/pricing.ts`): this package is a dependency of the app, not the other
 * way around, and `$type` is a compile-time assertion only — Postgres
 * validates nothing beyond "this is JSON" either way.
 */
type UsageBreakdownEntry = {
  agentId: string
  role: string
  slot: string
  /** The concrete registry entry that served this call. */
  modelId: string
  /** Present only when a fallback candidate served instead of the primary. */
  fallbackFrom?: string
  status: string
  inputTokens: number
  outputTokens: number
  cachedInputTokens: number
  reasoningTokens: number
  costMicroUsd: number
}

type UsageBreakdown = {
  tier: string
  entries: UsageBreakdownEntry[]
}

/**
 * Drizzle owns the schema for this database. Change a table here, then run
 * `pnpm db:push` to reconcile the branch against this file. Migration files are
 * not used while the project is in development — see AGENTS.md. Never issue ad
 * hoc DDL against a branch: a change that is not in this file is a change no
 * other branch will ever receive.
 */

/**
 * Better Auth's core schema — the four tables its Drizzle adapter reads and
 * writes directly, shaped to match what `better-auth@1.7.5` expects (verified
 * against `@better-auth/cli`'s own `generate` output rather than guessed —
 * re-run that command against a throwaway config before hand-editing any of
 * the column names or types below, since the adapter matches on these
 * property names, not on the underlying `pgTable` name).
 *
 * Authentication is social-only — GitHub and Google, configured in
 * `apps/web/lib/auth.ts` — so there is no `emailAndPassword` plugin and no
 * organization plugin. `user.id` is therefore the only tenant boundary this
 * application has: it is what `games.userId` and `turnUsage.userId` key on
 * now that a Clerk organization is no longer the unit of ownership.
 */

/**
 * One row per person who has ever signed in.
 *
 * `id` is generated by Better Auth itself at insert time, not by Postgres —
 * which is why it is a plain `text` primary key rather than a `uuid` column
 * with `defaultRandom()`, unlike every other primary key in this file.
 */
export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").default(false).notNull(),
  image: text("image"),
  /**
   * Owned by the `twoFactor` plugin in `apps/web/lib/auth.ts`. Stays false
   * after `/two-factor/enable` and only flips once the first TOTP code is
   * verified, so a half-finished enrollment never locks the user out.
   */
  twoFactorEnabled: boolean("two_factor_enabled").default(false),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at")
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
})

export type User = typeof user.$inferSelect
export type NewUser = typeof user.$inferInsert

/**
 * One row per browser session. `token` is the opaque value the session
 * cookie actually carries; `id` is the row's own identity and is never sent
 * to a client. Cascades on delete because a session cannot outlive the user
 * it authenticates.
 */
export const session = pgTable(
  "session",
  {
    id: text("id").primaryKey(),
    expiresAt: timestamp("expires_at").notNull(),
    token: text("token").notNull().unique(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text("ip_address"),
    userAgent: text("user_agent"),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
  },
  (table) => [index("session_userId_idx").on(table.userId)]
)

/**
 * One row per authentication method linked to a user — one GitHub identity,
 * one Google identity, and so on. Better Auth identifies the provider-side
 * account by the pair (`providerId`, `accountId`); `id` identifies this row
 * and is what account-management endpoints expect as their own `accountId`
 * argument. The OAuth token columns are nullable because a provider may not
 * return every one of them — GitHub's OAuth apps never issue a refresh token
 * — and `password` stays null for every row this application ever creates,
 * since there is no email/password provider configured; the column exists
 * only because the adapter's schema validation expects it regardless of
 * which providers are enabled.
 */
export const account = pgTable(
  "account",
  {
    id: text("id").primaryKey(),
    accountId: text("account_id").notNull(),
    providerId: text("provider_id").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    accessToken: text("access_token"),
    refreshToken: text("refresh_token"),
    idToken: text("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at"),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
    scope: text("scope"),
    password: text("password"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("account_userId_idx").on(table.userId)]
)

/**
 * Short-lived, single-purpose tokens — an OAuth state/PKCE value while a
 * social sign-in is in flight, for instance. Deliberately not tied to `user`
 * by a foreign key: a verification row can exist for an identifier before any
 * user row does, which is the reason this is a separate table rather than a
 * column on `user` in the first place.
 */
export const verification = pgTable(
  "verification",
  {
    id: text("id").primaryKey(),
    identifier: text("identifier").notNull(),
    value: text("value").notNull(),
    expiresAt: timestamp("expires_at").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at")
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index("verification_identifier_idx").on(table.identifier)]
)

/**
 * One row per user who has started TOTP enrollment — the `twoFactor` plugin's
 * own table, shaped to match `better-auth@1.7.5`'s plugin schema.
 *
 * `secret` holds the TOTP seed and `backupCodes` the recovery codes, both
 * encrypted with `BETTER_AUTH_SECRET` before they reach this table — rotating
 * that secret without a migration path makes every enrolled authenticator
 * unreadable. `verified` is false between `/two-factor/enable` and the first
 * successful code, which is how a pending enrollment is told apart from a
 * finished one. `failedVerificationCount` and `lockedUntil` back the plugin's
 * account-level lockout across sign-in challenges.
 */
export const twoFactor = pgTable(
  "two_factor",
  {
    id: text("id").primaryKey(),
    secret: text("secret").notNull(),
    backupCodes: text("backup_codes").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    verified: boolean("verified").default(true),
    failedVerificationCount: integer("failed_verification_count").default(0),
    lockedUntil: timestamp("locked_until"),
  },
  (table) => [
    index("twoFactor_secret_idx").on(table.secret),
    /**
     * Unique, though the plugin's own schema only asks for an index. The
     * plugin reads this table with an unordered `findOne` by user, so a second
     * row — two concurrent `/two-factor/enable` calls that both find nothing
     * and both insert — would let sign-in and step-up pick either secret at
     * random. The constraint turns that race into a failed insert instead.
     */
    uniqueIndex("twoFactor_userId_idx").on(table.userId),
  ]
)

/**
 * One row per registered passkey — the `@better-auth/passkey` plugin's own
 * table, shaped to match its `src/schema.ts` for this version.
 *
 * `publicKey` and `credentialID` are the WebAuthn credential itself: the
 * public half of the key pair and the id the authenticator answers to. Neither
 * is a secret (the private key never leaves the device), which is the whole
 * point of the scheme. `counter` is the authenticator's signature counter,
 * compared on every assertion to catch a cloned credential; `deviceType` and
 * `backedUp` say whether the credential is synced to a provider's cloud
 * ("multiDevice", backed up) or bound to this one device ("singleDevice").
 * `transports` is a comma-joined hint list — "internal", "usb", "hybrid" —
 * the browser uses to decide what to offer.
 *
 * `aaguid` identifies the authenticator MODEL, not the device or the user, and
 * is the only thing a name can be derived from when the user does not supply
 * one; the plugin's `getAuthenticatorName` maps the common ones. Apple's
 * default flow reports an all-zero AAGUID on purpose, so this is nullable both
 * in the plugin's schema and here.
 *
 * `name` is nullable for the same reason — the plugin lets a passkey be
 * registered unnamed and expects the UI to resolve a label at read time.
 */
export const passkey = pgTable(
  "passkey",
  {
    id: text("id").primaryKey(),
    name: text("name"),
    publicKey: text("public_key").notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    credentialID: text("credential_id").notNull(),
    counter: integer("counter").notNull(),
    deviceType: text("device_type").notNull(),
    backedUp: boolean("backed_up").notNull(),
    transports: text("transports"),
    createdAt: timestamp("created_at").defaultNow(),
    aaguid: text("aaguid"),
  },
  (table) => [
    index("passkey_userId_idx").on(table.userId),
    index("passkey_credentialID_idx").on(table.credentialID),
  ]
)

/**
 * Drizzle relations for Better Auth's joins (`advanced.database.joins` in
 * `apps/web/lib/auth.ts`). With joins on, the adapter loads a session and its
 * user in one relational query (`db.query.session.findFirst({ with: { user:
 * true } })`) instead of two round trips, so the relation keys must be exactly
 * the ones it asks for: `user` on `session`/`account`, `sessions`/`accounts`
 * on `user`. Without these, `getSession` throws rather than falling back.
 * Relations are query metadata only — they emit no DDL, so `db:push` has
 * nothing to apply for them.
 */
export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
  twoFactors: many(twoFactor),
  passkeys: many(passkey),
}))

export const passkeyRelations = relations(passkey, ({ one }) => ({
  user: one(user, { fields: [passkey.userId], references: [user.id] }),
}))

export const twoFactorRelations = relations(twoFactor, ({ one }) => ({
  user: one(user, { fields: [twoFactor.userId], references: [user.id] }),
}))

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}))

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}))

export const games = pgTable(
  "games",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    /**
     * The owning user's id. Every row is owned by exactly one user and every
     * query must filter on it — this is the tenant boundary, so a missing
     * predicate leaks another user's games. There is no organization concept
     * in this application: the individual account is the tenant, and this
     * column cascades when its user is deleted because a game has no
     * meaning without an owner to show it to.
     */
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),

    title: text("title").notNull(),

    /**
     * The game's entire chat thread, stored in the AI SDK's `UIMessage` shape —
     * the format `useChat` renders and posts — so a turn is a whole-document
     * rewrite rather than an append to a messages table. One game owns exactly
     * one thread, which is why this is a column and not a relation.
     *
     * `$type` is a compile-time assertion only: Postgres validates nothing
     * beyond "this is JSON", so anything read back from an older shape must be
     * treated as untrusted until validated.
     */
    messages: jsonb("messages").$type<UIMessage[]>().notNull().default([]),

    /**
     * The Trigger.dev chat Session backing this game's thread, as the browser
     * needs it back on page load. The Session outlives the runs it schedules,
     * so a tab opened tomorrow reconnects to the same conversation instead of
     * creating a second one.
     *
     * `chat_access_token` is the session-scoped PAT the transport authenticates
     * with; it expires, and the transport mints a fresh one through the
     * `mintChatAccessToken` action when it does, so a stale value here is a
     * round trip rather than a failure.
     */
    chatAccessToken: text("chat_access_token"),

    /**
     * Cursor into the Session's durable response stream. This is what replaces
     * stream-resumption plumbing: on reload the transport resubscribes from
     * here, so chunks already rendered are not redelivered and an in-flight
     * turn continues streaming.
     *
     * Written in the same statement as `messages` on purpose — a reload
     * between the two writes would resume from a stale cursor and render the
     * assistant's reply twice. It is keyed to the Session, not to a run, so it
     * is never cleared when a run ends.
     */
    lastEventId: text("last_event_id"),

    /**
     * The Daytona sandbox that hosts this game's files — one sandbox per game,
     * created on the chat's first turn.
     *
     * Nullable because the row exists before the sandbox does: `createGame`
     * writes the game, and the chat agent provisions the sandbox when the
     * conversation actually starts. A null here means "not provisioned yet",
     * which is also what a failed provision leaves behind — so read it as a
     * hint, and confirm with Daytona before trusting the sandbox is alive.
     */
    sandboxId: text("sandbox_id"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),

    /**
     * `$onUpdate` is applied by Drizzle on write, not by Postgres, so it only
     * fires for updates that go through Drizzle. Raw SQL against the branch
     * will leave this stale.
     */
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow()
      .$onUpdate(() => new Date()),

    /**
     * When this game was pinned, or null for one that never was — the
     * sidebar's own "is it pinned" flag doubles as its own sort key, so
     * pinning something later always outranks one pinned earlier. Set and
     * cleared through `setGamePinned`, never through `renameGame`'s sibling
     * update pattern.
     */
    pinnedAt: timestamp("pinned_at", { withTimezone: true }),
  },
  (table) => [
    /**
     * Serves the app's dominant read: one user's games, newest first (the
     * sidebar's "Recents"). The leading `user_id` column also makes this
     * usable for a plain `where user_id = ?`, so no separate single-column
     * index is warranted.
     */
    index("games_user_id_created_at_idx").on(
      table.userId,
      table.createdAt.desc()
    ),
  ]
)

export type Game = typeof games.$inferSelect
export type NewGame = typeof games.$inferInsert

/**
 * One row per completed chat turn: what it spent, and what that is estimated to
 * have cost. Append-only — nothing in the application updates or deletes a row
 * here, because the question this table answers is historical ("what did this
 * game cost to build?") and a mutable answer to that is worth nothing.
 *
 * This is measurement, not billing. No price is charged from these numbers and
 * no access is gated on them; they exist so the real cost-per-game can be
 * learned from production before anything is priced on a guess.
 */
export const turnUsage = pgTable(
  "turn_usage",
  {
    id: uuid("id").primaryKey().defaultRandom(),

    /**
     * The game this turn belonged to — deliberately *not* a foreign key.
     *
     * Both available referential actions are wrong here. `restrict` would make
     * the ledger block the app's delete-game feature, so a player could not
     * remove their own game once it had cost anything. `cascade` would erase
     * the cost record along with it, which is worse: the money was really
     * spent, and a deletion in the product does not un-spend it.
     *
     * So the ledger outlives the game it describes, and a lookup against
     * `games` is allowed to find nothing. Read this as an identifier, not as a
     * relation.
     */
    gameId: uuid("game_id").notNull(),

    /**
     * Copied from `games.userId` at write time rather than joined for.
     *
     * Denormalized for the same reason the game id is not a key: this is the
     * boundary anything is ever eventually billed to, and it has to survive the
     * game's deletion. Resolving the user through `games` at read time would
     * make every deleted game's spend fall out of its total — silently, and
     * only for the users who delete things.
     *
     * Deliberately not a foreign key to `user.id` either, and for the same
     * reason `gameId` above is not one: `restrict` would block account
     * deletion, and `cascade` would erase spend history that genuinely
     * happened the moment a user's row goes away — worse than an orphaned
     * ledger row, because the money was real and the account being gone
     * does not un-spend it.
     */
    userId: text("user_id").notNull(),

    modelId: text("model_id").notNull(),

    /** The turn's 0-indexed position within its chat, as `onTurnComplete`
     * reports it. Ordering, not identity: a retried run can repeat a number. */
    turn: integer("turn").notNull(),

    /**
     * The Trigger.dev run that produced the turn. Kept so a surprising row can
     * be opened in the dashboard and read against the run's actual steps —
     * which is the only way to reconcile an estimate here with what the
     * provider really did.
     */
    runId: text("run_id").notNull(),

    inputTokens: integer("input_tokens").notNull().default(0),
    outputTokens: integer("output_tokens").notNull().default(0),
    cachedInputTokens: integer("cached_input_tokens").notNull().default(0),
    reasoningTokens: integer("reasoning_tokens").notNull().default(0),

    /**
     * The turn's ESTIMATED cost, in millionths of a USD.
     *
     * Integer micro-dollars rather than a float or a numeric, because money
     * summed over thousands of rows must not accumulate binary rounding error —
     * and because the unit has to be small enough that a single cheap turn is
     * not rounded to zero cents.
     *
     * `int4` caps one row near $2,147, which `stopWhen: stepCountIs(25)` puts
     * comfortably out of reach of any single turn. Aggregates are safe too:
     * Postgres widens `sum(int4)` to `bigint`, so a rollup cannot overflow the
     * column's own type.
     */
    costMicroUsd: integer("cost_micro_usd").notNull(),

    /**
     * The per-agent detail behind the totals on this row: which tier the turn
     * ran on, and, per run, its role, concrete registry entry and priced
     * cost — the orchestrator today, every dispatched sub-agent from unit 2a
     * onward. Nullable because a row written before this column existed has
     * none, and because a turn that never dispatched anything still writes a
     * one-entry breakdown rather than an empty one.
     *
     * Kept alongside the aggregate columns rather than instead of them: the
     * aggregates answer "what did this turn cost" with an index-friendly
     * scalar, and this answers "which model, in what proportion" without
     * requiring every reader to parse jsonb just to sum a number the row
     * already has. See `turn-usage-accounting`'s Per-Sub-Agent Usage
     * Breakdown Retained requirement and decision 10 in `design.md`.
     */
    usageBreakdown: jsonb("usage_breakdown").$type<UsageBreakdown>(),

    /**
     * Which version of the in-repo rate table produced `costMicroUsd`.
     *
     * This is what makes the number auditable instead of merely stored. Rates
     * change on schedules nobody controls — Gemini 3.8 Flash doubles on
     * 2027-01-01 when its introductory pricing ends — so without knowing which
     * rates were in effect, a row's estimate can never be re-derived, explained
     * to anyone, or corrected in bulk once a rate turns out to have been wrong.
     */
    rateVersion: text("rate_version").notNull(),

    /**
     * How many credits this turn consumed — the customer-facing unit, stored
     * rather than derived from `cost_micro_usd` on read.
     *
     * The conversion is not a constant of nature. It is a markup somebody
     * chose, and it will be chosen differently at some point. Recomputing this
     * number later would apply today's markup to a turn that was sold under
     * yesterday's, silently rewriting how much every historical turn cost the
     * customer — including turns already paid for. A row has to stay
     * explainable with the economics that were in force when it was written,
     * and the only way that holds is if the answer is written down.
     *
     * `rate_version` covers this too, and deliberately: the markup constant
     * lives in the same rate file as the per-model rates, so the version that
     * explains `cost_micro_usd` is the same version that explains this column.
     * There is no second version to keep in step.
     */
    credits: integer("credits").notNull().default(0),

    /**
     * When Polar accepted the usage event for this row, or null if it never
     * did. This is the repair handle.
     *
     * `credits > 0 and credits_ingested_at is null` is usage this application
     * charged for internally and never told Polar about — the exact query a
     * reconciliation job runs, and the exact set of rows it has to replay.
     * Without this column the ingest is fire-and-forget in the worst sense: a
     * failed call leaves behind a row indistinguishable from a successful one,
     * so the backlog is not merely unrepaired but unfindable. Nothing in the
     * system would ever surface it, and the money is simply gone.
     */
    creditsIngestedAt: timestamp("credits_ingested_at", { withTimezone: true }),

    /** Why the model stopped, when the provider said. Nullable because a turn
     * can complete without one — an aborted stream reports nothing. */
    finishReason: text("finish_reason"),

    /** Whether the player stopped this turn mid-generation. A stopped turn
     * still costs what it had already produced, so it is recorded, but it is
     * not comparable to one that ran to completion. */
    stopped: boolean("stopped").notNull().default(false),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    /**
     * Serves the rollup this table exists for: one user's spend over a
     * window, newest first. The leading `user_id` also covers a plain
     * `where user_id = ?` total, so no second index is warranted for it.
     */
    index("turn_usage_user_id_created_at_idx").on(
      table.userId,
      table.createdAt.desc()
    ),

    /**
     * Serves the other question — what one game cost — which is a scan of every
     * turn it ever ran. Separate from the index above because `user_id` does
     * not prefix it: a game's rows are a narrow slice of its user's, and
     * reaching them through the user index would read that user's whole
     * history to throw nearly all of it away.
     */
    index("turn_usage_game_id_idx").on(table.gameId),
  ]
)

export type TurnUsage = typeof turnUsage.$inferSelect
export type NewTurnUsage = typeof turnUsage.$inferInsert
