"use client"

import { useEffect, useRef, useState } from "react"
import { AlertCircleIcon, Copy01Icon } from "@hugeicons/core-free-icons"
import { HugeiconsIcon } from "@hugeicons/react"
import QRCode from "react-qr-code"
import { useTranslations } from "next-intl"
import {
  Alert,
  AlertDescription,
  AlertTitle,
} from "@workspace/ui/components/alert"
import { Button } from "@workspace/ui/components/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@workspace/ui/components/dialog"
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
} from "@workspace/ui/components/input-otp"
import { Separator } from "@workspace/ui/components/separator"

import { authClient } from "@/lib/auth-client"
import { RecoveryCodes } from "@/components/settings/recovery-codes"
import { Spinner } from "@/components/localized-spinner"

/**
 * Splits a TOTP secret into 4-character blocks — `ABCD EFGH IJKL` rather
 * than one unbroken run — purely for reading it back into an authenticator
 * app that has no QR scanner handy. `secret` never contains spaces of its
 * own (it is base32, generated by Better Auth), so `.replace` here can only
 * ever add them.
 */
function formatSecret(secret: string): string {
  return secret.replace(/(.{4})/g, "$1 ").trim()
}

/**
 * The response of the one `authClient.twoFactor.enable` call behind the
 * dialog currently open — owned by `useTwoFactorEnrollment` below, read by
 * `TwoFactorSetupDialog`.
 */
export type Enrollment =
  | { status: "loading" }
  | { status: "error" }
  | { status: "ready"; totpURI: string; backupCodes: string[] }

/**
 * Starts and tracks TOTP enrollment, driven by clicks only.
 *
 * # Why `enable` runs from an event handler, never an effect
 *
 * Every `enable` call mints a new secret and overwrites the unverified one
 * already stored. Two calls for one dialog therefore race: the QR code shows
 * whichever response arrived last, the server keeps whichever write landed
 * last, and nothing makes those the same secret — the user enrolls a secret
 * the server no longer has, and is locked out at the next sign-in. An effect
 * keyed on `open` is exactly where a second call sneaks in (React Strict
 * Mode replays effects in development; a remount re-runs them), so `start`
 * is only ever called from the "Enable" and "Retry" clicks.
 *
 * `requestIdRef` covers what remains: a response that resolves after the
 * dialog closed, or after a newer "Retry", is dropped instead of shown.
 */
export function useTwoFactorEnrollment() {
  const [enrollment, setEnrollment] = useState<Enrollment>({
    status: "loading",
  })
  const requestIdRef = useRef(0)
  const mountedRef = useRef(true)

  useEffect(() => {
    mountedRef.current = true
    return () => {
      mountedRef.current = false
    }
  }, [])

  async function start() {
    if (!mountedRef.current) return

    const requestId = ++requestIdRef.current
    setEnrollment({ status: "loading" })

    try {
      const { data, error } = await authClient.twoFactor.enable({})

      if (!mountedRef.current || requestId !== requestIdRef.current) return

      // `method` defaults to `"totp"` server-side (nothing here ever passes
      // `"otp"`), but the response type covers both, so `data.totpURI` is
      // only visible once this narrows on `method`.
      if (error || !data || data.method !== "totp") {
        setEnrollment({ status: "error" })
        return
      }

      setEnrollment({
        status: "ready",
        totpURI: data.totpURI,
        backupCodes: data.backupCodes,
      })
    } catch {
      if (mountedRef.current && requestId === requestIdRef.current) {
        setEnrollment({ status: "error" })
      }
    }
  }

  /** Drops the secret and codes, and orphans any request still in flight. */
  function discard() {
    requestIdRef.current++
    if (mountedRef.current) setEnrollment({ status: "loading" })
  }

  return { enrollment, start, discard }
}

/**
 * The full TOTP enrollment flow, opened from `security-section.tsx`'s
 * "Enable" button, which also calls `useTwoFactorEnrollment().start` — this
 * dialog only renders the `enrollment` it is handed.
 *
 * # Why the secret and codes never leave memory
 *
 * The URI embeds the raw TOTP secret, and the codes are a one-time
 * credential. Neither is written to storage or logged anywhere in this
 * tree, and both disappear when the dialog closes: every close path ends in
 * `onOpenChange(false)`, which the caller answers with `discard()`.
 */
export function TwoFactorSetupDialog({
  open,
  onOpenChange,
  enrollment,
  onRetry,
}: {
  open: boolean
  onOpenChange: (open: boolean) => void
  enrollment: Enrollment
  onRetry: () => void
}) {
  const t = useTranslations("Settings")
  const [verified, setVerified] = useState(false)
  const [code, setCode] = useState("")
  const [verifyError, setVerifyError] = useState<string | null>(null)
  const [verifying, setVerifying] = useState(false)
  const [revokingOthers, setRevokingOthers] = useState(false)
  const verificationAttemptRef = useRef(0)
  const mountedRef = useRef(true)

  useEffect(() => {
    mountedRef.current = true
    return () => {
      mountedRef.current = false
    }
  }, [])

  const phase =
    enrollment.status !== "ready"
      ? enrollment.status
      : verified
        ? "codes"
        : "setup"
  const totpURI = enrollment.status === "ready" ? enrollment.totpURI : null
  const backupCodes =
    enrollment.status === "ready" ? enrollment.backupCodes : []

  function retryEnrollment() {
    setVerifyError(null)
    onRetry()
  }

  function resetState() {
    verificationAttemptRef.current++
    setVerified(false)
    setCode("")
    setVerifyError(null)
  }

  function handleCancel() {
    if (verifying || revokingOthers) return
    resetState()
    onOpenChange(false)
  }

  function handleDone() {
    if (revokingOthers) return
    resetState()
    onOpenChange(false)
  }

  async function handleConfirm() {
    const attemptId = ++verificationAttemptRef.current
    setVerifying(true)
    setVerifyError(null)

    try {
      const { error } = await authClient.twoFactor.verifyTotp({ code })
      if (!mountedRef.current || attemptId !== verificationAttemptRef.current) {
        return
      }

      if (error) {
        setCode("")
        setVerifyError(
          error.code === "INVALID_CODE"
            ? t("invalidCode")
            : t("genericError")
        )
        return
      }

      /**
       * No manual session refetch: `twoFactorClient`'s `atomListeners` already
       * notify `useSession`'s signal for every successful `/two-factor/*` call
       * (see `better-auth/dist/plugins/two-factor/client.mjs`), so the badge
       * in `security-section.tsx` updates on its own the moment this resolves.
       */
      setVerified(true)
    } catch {
      if (mountedRef.current && attemptId === verificationAttemptRef.current) {
        setCode("")
        setVerifyError(t("genericError"))
      }
    } finally {
      if (mountedRef.current && attemptId === verificationAttemptRef.current) {
        setVerifying(false)
      }
    }
  }

  async function signOutOtherSessions() {
    setRevokingOthers(true)
    setVerifyError(null)
    try {
      const { error } = await authClient.revokeOtherSessions()
      if (error && mountedRef.current) {
        setVerifyError(
          error.message ?? t("couldNotRevokeOtherSessions")
        )
      }
    } catch {
      if (mountedRef.current) {
        setVerifyError(t("couldNotRevokeOtherSessions"))
      }
    } finally {
      if (mountedRef.current) setRevokingOthers(false)
    }
  }

  const secret = totpURI ? new URL(totpURI).searchParams.get("secret") : null

  return (
    <Dialog
      open={open}
      onOpenChange={(nextOpen, eventDetails) => {
        // Step 3 shows a one-time set of recovery codes: losing them to a
        // stray Escape or an outside click is unrecoverable, so only the
        // explicit "Done" button (`handleDone`) is allowed to close from
        // there.
        if (!nextOpen && (phase === "codes" || verifying || revokingOthers)) {
          eventDetails.cancel()
          return
        }

        if (!nextOpen) {
          resetState()
        }

        onOpenChange(nextOpen)
      }}
    >
      <DialogContent
        showCloseButton={phase !== "codes" && !verifying && !revokingOthers}
      >
        <DialogHeader>
          <DialogTitle>
            {phase === "codes"
              ? t("saveRecoveryCodes")
              : t("authenticatorSetup")}
          </DialogTitle>
          <DialogDescription>
            {phase === "codes"
              ? t("twoFactorEnabledDescription")
              : t("authenticatorSetupDescription")}
          </DialogDescription>
        </DialogHeader>

        {phase === "loading" && (
          <div className="flex items-center justify-center py-8">
            <Spinner className="size-6" />
          </div>
        )}

        {phase === "error" && (
          <div className="flex flex-col gap-4">
            <Alert variant="destructive">
              <HugeiconsIcon icon={AlertCircleIcon} />
              <AlertTitle>{t("couldNotStartSetup")}</AlertTitle>
              <AlertDescription>
                {t("setupFailedDescription")}
              </AlertDescription>
            </Alert>
            <Button type="button" variant="outline" onClick={retryEnrollment}>
              {t("retry")}
            </Button>
          </div>
        )}

        {phase === "setup" && totpURI && (
          <div className="flex flex-col gap-6">
            <div className="flex flex-col gap-3">
              <p className="text-sm font-medium">{t("stepScanQr")}</p>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-[auto_1fr] sm:items-center">
                <div className="w-fit rounded-2xl bg-white p-3">
                  <QRCode value={totpURI} size={128} />
                </div>
                <div className="flex flex-col gap-2">
                  <p className="text-sm text-muted-foreground">
                    {t("cannotScanQr")}
                  </p>
                  <div className="flex items-center gap-2">
                    <code className="flex-1 rounded-2xl bg-muted px-3 py-2 font-mono text-sm break-all text-muted-foreground">
                      {secret ? formatSecret(secret) : ""}
                    </code>
                    <Button
                      type="button"
                      variant="outline"
                      size="icon-sm"
                      aria-label={t("copySecret")}
                      onClick={() =>
                        secret && navigator.clipboard.writeText(secret)
                      }
                    >
                      <HugeiconsIcon icon={Copy01Icon} strokeWidth={2} />
                    </Button>
                  </div>
                </div>
              </div>
            </div>

            <Separator />

            <div className="flex flex-col gap-3">
              <p className="text-sm font-medium">
                {t("stepVerificationCode")}
              </p>
              <p className="text-sm text-muted-foreground">
                {t("enterCodeToVerify")}
              </p>
              <InputOTP
                maxLength={6}
                aria-label={t("enterCodeToVerify")}
                value={code}
                onChange={(value) => {
                  setCode(value)
                  setVerifyError(null)
                }}
                disabled={verifying}
              >
                <InputOTPGroup>
                  {Array.from({ length: 6 }).map((_, index) => (
                    <InputOTPSlot key={index} index={index} />
                  ))}
                </InputOTPGroup>
              </InputOTP>
              {verifyError && (
                <p className="text-sm text-destructive">{verifyError}</p>
              )}
            </div>
          </div>
        )}

        {phase === "codes" && (
          <div className="flex flex-col gap-4">
            <RecoveryCodes codes={backupCodes} onDone={handleDone} />
            <Separator />
            <div className="flex flex-col gap-2">
              <p className="text-sm text-muted-foreground">
                {t("twoFactorDoesNotSignOut")}
              </p>
              <Button
                type="button"
                variant="outline"
                className="self-start"
                disabled={revokingOthers}
                onClick={signOutOtherSessions}
              >
                {revokingOthers && <Spinner />}
                {t("signOutOtherSessions")}
              </Button>
              {verifyError && (
                <p className="text-sm text-destructive">{verifyError}</p>
              )}
            </div>
          </div>
        )}

        {phase === "setup" && (
          <DialogFooter>
            <Button
              type="button"
              variant="outline"
              disabled={verifying || revokingOthers}
              onClick={handleCancel}
            >
              {t("cancel")}
            </Button>
            <Button
              type="button"
              onClick={handleConfirm}
              disabled={code.length !== 6 || verifying}
            >
              {verifying && <Spinner />}
              {t("confirm")}
            </Button>
          </DialogFooter>
        )}
      </DialogContent>
    </Dialog>
  )
}
